version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn FominFishing.wsgi:application --workers 3 --bind 0.0.0.0:8050"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8050
  nginx:
    build: ./nginx
    ports:
      - 8050:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static
volumes:
  static_volume:
  media_volume:
