# Generated by Django 4.0.3 on 2022-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_photo_path_alter_photo_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='in_main_page',
            field=models.BooleanField(default=False, verbose_name='На главной странице'),
        ),
    ]
