# Generated by Django 4.0.3 on 2022-05-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'Календарь рыбалок'},
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='date',
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_date',
            field=models.CharField(default=1, max_length=150, verbose_name='Дата окончания рыбалки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_date',
            field=models.CharField(default=1, max_length=150, verbose_name='Дата начала рыбалки'),
            preserve_default=False,
        ),
    ]
