# Generated by Django 4.0.3 on 2022-05-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_calendar_options_remove_calendar_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания рыбалки'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала рыбалки'),
        ),
    ]
