# Generated by Django 4.0.3 on 2022-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_calendar_end_date_alter_calendar_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания рыбалки'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала рыбалки'),
        ),
    ]
