# Generated by Django 4.0.3 on 2022-05-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_calendar_end_date_alter_calendar_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание события'),
        ),
    ]
