# Generated by Django 4.0.3 on 2022-05-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_calendar_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='frame',
            field=models.CharField(max_length=150, verbose_name='Ссылка на youtube'),
        ),
    ]
